spring:
  application:
    name: partner world
  cloud:
    gcp:
      datastore:
        host: 0.0.0.0:8081
        project-id: myproject
        namespace: de
logging:
  level:
    com.google.cloud.datastore: DEBUG

# custom properties
custom:
  auditing:
    enabled: false