spring:
  application:
    name: partnerworld
  output:
    ansi:
      enabled: ALWAYS
  cache:
    type: caffeine
logging:
  level:
    io.ablil: DEBUG
    org.springframework.web: DEBUG
    com.google.cloud.datastore: DEBUG
    org.springframework.cache: TRACE

# custom properties
custom:
  auditing:
    enabled: false

springdoc:
  default-produces-media-type: application/json
  packages-to-exclude: 'io.ablil' # serve the yaml file directly instead of scanning generated code
  swagger-ui:
    urls:
      - url: 'oas/partnerworld.yaml'
        name: partnerworld
        display-name: partnerworld

---
# emulator config
spring:
  config:
    activate:
      on-profile: emulator
  cloud:
    gcp:
      datastore:
        host: 0.0.0.0:8081
        project-id: my-project # configured on the container

---
# cloud config
spring:
  config:
    activate:
      on-profile: cloud
  cloud:
    gcp:
      project-id: ${PROJECT_ID:gcp-training-playground-405915}
      datastore:
        database-id: ${DATABASE_ID:partnerworld-development}
