
spring:
  application:
    name: partnerworld
  output:
    ansi:
      enabled: ALWAYS
  cache:
    type: caffeine
  cloud:
    gcp:
      project-id: ${PROJECT_ID:gcp-training-playground-405915}
      datastore:
        database-id: ${DATABASE_ID:partnerworld}
logging:
  level:
    io.ablil: DEBUG
    org.springframework.web: DEBUG
    com.google.cloud.datastore: DEBUG
    org.springframework.cache: TRACE

# custom properties
custom:
  auditing:
    enabled: false

springdoc:
  default-produces-media-type: application/json
  packages-to-exclude: 'io.ablil' # serve the yaml file directly instead of scanning generated code
  swagger-ui:
    urls:
      - url: 'oas/partnerworld.yaml'
        name: partnerworld
        display-name: partnerworld