name: 'CI/CD'

permissions: write-all

on:
  push:
    branches:
      - main
  pull_request:
    branches:
     - main

env:
  TERRAFORM_DIR: IaC/terraform
  TERRAFORM_VARS_FILE: ../environments/development.auto.tfvars # relative to path above

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - run: docker login ghcr.io -u USERNAME -p ${{ secrets.GITHUB_TOKEN }}
      - run: ./gradlew jibDockerBuild
      - run: docker tag partnerworld:latest ghcr.io/ablil/partnerworld:${{ github.head_ref }} && docker push $_
        if: github.ref != 'refs/heads/main'
      - run: docker tag partnerworld:latest ghcr.io/ablil/partnerworld:latest && docker push $_
        if: github.ref == 'refs/heads/main'

  terraform:
    runs-on: ubuntu-latest
    needs: docker # wait for docker image to be pushed to ghcr
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.HCP_TERRAFORM_API_KEY }}
      - name: terraform init
        run: terraform -chdir=$TERRAFORM_DIR init
      - name: terraform plan
        run: terraform -chdir=$TERRAFORM_DIR plan -var-file=$TERRAFORM_VARS_FILE
      - name: terraform apply
        run: terraform -chdir=$TERRAFORM_DIR apply -var-file=$TERRAFORM_VARS_FILE --auto-approve
        if: github.ref == 'refs/heads/main'

  gemini-review:
    if: startsWith(github.ref, 'refs/pull')
    runs-on: ubuntu-latest
    steps:
      - name: Gemini code review
        uses: ablil/gemini-code-review@v0.5.10
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
