name: AI Code review

on:
  pull_request:

permissions: write-all

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: ablil/gemini-code-review@main
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
