name: Continuous integration

permissions: write-all

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
     - main

env:
  SERVICE_NAME: partnerworld
  DOCKER_TAG: ${{ github.ref == 'refs/heads/main' && 'latest' || github.head_ref }}

  TF_CLOUD_ORGANIZATION: ablil-org
  TF_WORKSPACE: partnerworld
  TF_API_TOKEN: ${{ secrets.HCP_TERRAFORM_API_KEY }}

  GCP_PROJECT_ID: gcp-training-playground-405915
  GCP_REGION: europe-west3

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4.6.0
        with:
          java-version: 17
          distribution: 'corretto'
          cache: gradle
      - run: docker login ghcr.io -u USERNAME -p ${{ secrets.GITHUB_TOKEN }}
      - run: ./gradlew build -x test -Ptag=$DOCKER_TAG
      - run: echo '# Hello world' >> $GITHUB_STEP_SUMMARY

  terraform:
    runs-on: ubuntu-latest
    environment:
      name: terraform-run
      url: ${{ steps.plan.outputs.run_link }}
    defaults:
      run:
        working-directory: IaC/src/main/terraform
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        id: plan
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          plan_only: ${{ github.ref != 'refs/heads/main' }}
      - uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          run: ${{ steps.plan.outputs.run_id }}
          comment: 'Apply run from Github workflow ${{ github.sha }}'


  cloudrun-deployment:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [gradle-build, terraform]
    environment:
      name: cloudrun
      url: ${{ steps.cloudrun.outputs.cloudrun_url }}
    steps:
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - uses: 'google-github-actions/setup-gcloud@v2'
      - run: |
          gcloud run services update $SERVICE_NAME \
            --project=$GCP_PROJECT_ID \
            --region=$GCP_REGION \
            --image=$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/ghcr/ablil/$SERVICE_NAME:$DOCKER_TAG
      - id: cloudrun
        run: |
          url=$(gcloud run services $SERVICE_NAME --region=$GCP_REGION --project=$GCP_PROJECT --format=json | jq '.status.url')
          echo "cloudrun_url=$url" >> $GITHUB_OUTPUT
