name: convert TODOs to Github issues

on:
  pull_request:
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '2'

      - run: bash scripts.sh