name: convert TODOs to Github issues

on:
  pull_request:
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Identify Base SHA
        id: base
        run: |
          BASE_SHA=$(git merge-base origin/${{ github.event.pull_request.base.ref }} origin/${{ github.event.pull_request.head.ref }})
          echo "BASE_SHA=$BASE_SHA" >> $GITHUB_ENV

    # TODO: add this as an example to dotfiles repository
      - uses: ablil/dotfiles/git/actions/todos2issues@master
        with:
          left_ref: ${{ steps.base.outputs.BASE_SHA }}
          right_ref: ${{ github.head_ref }}