name: convert TODOs to Github issues

on:
  pull_request:
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

    # TODO: add this as an example to dotfiles repository
      - uses: ablil/dotfiles/git/actions/todos2issues@master
        with:
          left_ref: ${{ github.base_ref }}
          right_ref: ${{ github.head_ref }}