name: Github issues from Todos

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

permissions: write-all

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: ablil/dotfiles/git/actions/todos2issues@master
        with:
          left_ref: HEAD^
          right_ref: HEAD

