name: 'Deploy docker image'

permissions: write-all

on:
  push:
    branches:
      - main
  pull_request:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login ghcr.io -u USERNAME -p ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - run: ./gradlew jibDockerBuild
      - run: docker tag partnerworld:latest ghcr.io/ablil/partnerworld:${{ github.head_ref }} && docker push $_
        if: github.ref != 'refs/heads/main'
      - run: docker tag partnerworld:latest ghcr.io/ablil/partnerworld:latest && docker push $_
        if: github.ref == 'refs/heads/main'
