name: 'terraform'


on:
  push:
    branches:
      - main
  pull_request:
    branches:
     - main

env:
  TERRAFORM_DIR: IaC/terraform
  TERRAFORM_VARS_FILE: ../environments/development.auto.tfvars # relative to path above

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.HCP_TERRAFORM_API_KEY }}
      - name: terraform init
        run: terraform -chdir=$TERRAFORM_DIR init
      - name: terraform plan
        run: terraform -chdir=$TERRAFORM_DIR plan -var-file=$TERRAFORM_VARS_FILE
      - name: terraform apply
        run: terraform -chdir=$TERRAFORM_DIR apply -var-file=$TERRAFORM_VARS_FILE --auto-approve
        if: github.ref == 'refs/heads/main'
